/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiNewsRouteImport } from './routes/ai-news'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PromptLibraryRouteImport } from './routes/prompt-library'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AiNewsIndexRouteImport } from './routes/ai-news.index'
import { Route as AiNewsIdRouteImport } from './routes/ai-news.$id'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as PromptLibraryIndexRouteImport } from './routes/prompt-library.index'
import { Route as PromptLibraryIdRouteImport } from './routes/prompt-library.$id'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardCoursesSlugRouteImport } from './routes/_authenticated/dashboard.courses.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiNewsRoute = AiNewsRouteImport.update({
  id: '/ai-news',
  path: '/ai-news',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptLibraryRoute = PromptLibraryRouteImport.update({
  id: '/prompt-library',
  path: '/prompt-library',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AiNewsIndexRoute = AiNewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AiNewsRoute,
} as any)
const AiNewsIdRoute = AiNewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AiNewsRoute,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptLibraryIndexRoute = PromptLibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PromptLibraryRoute,
} as any)
const PromptLibraryIdRoute = PromptLibraryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PromptLibraryRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCoursesSlugRoute =
  AuthenticatedDashboardCoursesSlugRouteImport.update({
    id: '/courses/$slug',
    path: '/courses/$slug',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-news': typeof AiNewsRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/prompt-library': typeof PromptLibraryRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/ai-news/$id': typeof AiNewsIdRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/prompt-library/$id': typeof PromptLibraryIdRoute
  '/ai-news/': typeof AiNewsIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/prompt-library/': typeof PromptLibraryIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/courses/$slug': typeof AuthenticatedDashboardCoursesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-news/$id': typeof AiNewsIdRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/prompt-library/$id': typeof PromptLibraryIdRoute
  '/ai-news': typeof AiNewsIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/prompt-library': typeof PromptLibraryIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/courses/$slug': typeof AuthenticatedDashboardCoursesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/ai-news': typeof AiNewsRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/prompt-library': typeof PromptLibraryRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/ai-news/$id': typeof AiNewsIdRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/prompt-library/$id': typeof PromptLibraryIdRoute
  '/ai-news/': typeof AiNewsIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/prompt-library/': typeof PromptLibraryIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/courses/$slug': typeof AuthenticatedDashboardCoursesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-news'
    | '/auth'
    | '/contact'
    | '/prompt-library'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/ai-news/$id'
    | '/checkout/$slug'
    | '/courses/$slug'
    | '/prompt-library/$id'
    | '/ai-news/'
    | '/courses/'
    | '/prompt-library/'
    | '/dashboard/'
    | '/dashboard/courses/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/admin'
    | '/ai-news/$id'
    | '/checkout/$slug'
    | '/courses/$slug'
    | '/prompt-library/$id'
    | '/ai-news'
    | '/courses'
    | '/prompt-library'
    | '/dashboard'
    | '/dashboard/courses/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/ai-news'
    | '/auth'
    | '/contact'
    | '/prompt-library'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/ai-news/$id'
    | '/checkout/$slug'
    | '/courses/$slug'
    | '/prompt-library/$id'
    | '/ai-news/'
    | '/courses/'
    | '/prompt-library/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/courses/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AiNewsRoute: typeof AiNewsRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  PromptLibraryRoute: typeof PromptLibraryRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-news': {
      id: '/ai-news'
      path: '/ai-news'
      fullPath: '/ai-news'
      preLoaderRoute: typeof AiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-library': {
      id: '/prompt-library'
      path: '/prompt-library'
      fullPath: '/prompt-library'
      preLoaderRoute: typeof PromptLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/ai-news/': {
      id: '/ai-news/'
      path: '/'
      fullPath: '/ai-news/'
      preLoaderRoute: typeof AiNewsIndexRouteImport
      parentRoute: typeof AiNewsRoute
    }
    '/ai-news/$id': {
      id: '/ai-news/$id'
      path: '/$id'
      fullPath: '/ai-news/$id'
      preLoaderRoute: typeof AiNewsIdRouteImport
      parentRoute: typeof AiNewsRoute
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-library/': {
      id: '/prompt-library/'
      path: '/'
      fullPath: '/prompt-library/'
      preLoaderRoute: typeof PromptLibraryIndexRouteImport
      parentRoute: typeof PromptLibraryRoute
    }
    '/prompt-library/$id': {
      id: '/prompt-library/$id'
      path: '/$id'
      fullPath: '/prompt-library/$id'
      preLoaderRoute: typeof PromptLibraryIdRouteImport
      parentRoute: typeof PromptLibraryRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/courses/$slug': {
      id: '/_authenticated/dashboard/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/dashboard/courses/$slug'
      preLoaderRoute: typeof AuthenticatedDashboardCoursesSlugRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardCoursesSlugRoute: typeof AuthenticatedDashboardCoursesSlugRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardCoursesSlugRoute:
      AuthenticatedDashboardCoursesSlugRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AiNewsRouteChildren {
  AiNewsIdRoute: typeof AiNewsIdRoute
  AiNewsIndexRoute: typeof AiNewsIndexRoute
}

const AiNewsRouteChildren: AiNewsRouteChildren = {
  AiNewsIdRoute: AiNewsIdRoute,
  AiNewsIndexRoute: AiNewsIndexRoute,
}

const AiNewsRouteWithChildren =
  AiNewsRoute._addFileChildren(AiNewsRouteChildren)

interface PromptLibraryRouteChildren {
  PromptLibraryIdRoute: typeof PromptLibraryIdRoute
  PromptLibraryIndexRoute: typeof PromptLibraryIndexRoute
}

const PromptLibraryRouteChildren: PromptLibraryRouteChildren = {
  PromptLibraryIdRoute: PromptLibraryIdRoute,
  PromptLibraryIndexRoute: PromptLibraryIndexRoute,
}

const PromptLibraryRouteWithChildren = PromptLibraryRoute._addFileChildren(
  PromptLibraryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AiNewsRoute: AiNewsRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  PromptLibraryRoute: PromptLibraryRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
